# Generated by Django 5.0.3 on 2024-09-08 11:58

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_user_profile_user_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default=accounts.models.generate_random_username, max_length=150, null=True, unique=True),
        ),
    ]
