# Generated by Django 5.0.3 on 2024-09-08 12:00

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=accounts.models.generate_random_username, max_length=150, unique=True),
        ),
    ]
