# Base image for development
FROM node:22-alpine AS development

# Set the working directory
WORKDIR /app

# Copy the application code
COPY . /app/

# Install dependencies
RUN npm install

# Expose port for development
EXPOSE 3000

# Set default environment to development
ENV NODE_ENV=development

# Start the development server
CMD ["npm", "run", "dev"]
