# Generated by Django 5.1.4 on 2025-03-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_usage', '0002_billingplan_userbilling'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbilling',
            name='last_billed_month',
            field=models.DateField(blank=True, null=True),
        ),
    ]
