# Generated by Django 5.1.4 on 2025-03-30 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_usage', '0003_userbilling_last_billed_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingplan',
            old_name='version_history_days',
            new_name='version_history_limit',
        ),
    ]
