# Generated by Django 5.1.2 on 2024-11-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vars', '0002_alter_environmentvariable_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variableversion',
            name='version',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
