# Generated by Django 5.1.2 on 2024-11-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vars', '0005_alter_environmentvariable_latest_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentvariable',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
