# Generated by Django 5.1.4 on 2025-03-29 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vars', '0007_environmentvariable_unique_name_per_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentvariable',
            name='latest_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='latest_for_variable', to='vars.variableversion'),
        ),
    ]
